name: CICD

on:
  push:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Actualizar pip
        run: |
          python -m pip install --upgrade pip
      - name: Verificar archivo requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt no encontrado. No se ejecutará la acción."
            exit 0
          fi
      - name: Instalar dependencias
        run: |
          python -m pip install -r requirements.txt

      - name: Correr tests
        run: |
          pytest --cov=. --cov-report xml

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
      REGISTRY_SPACE: ${{ secrets.REGISTRY_SPACE }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verificar archivo Dockerfile
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile no encontrado. No se ejecutará la acción."
            exit 0
          fi
      - name: Autenticarse en el registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_HOST -u $REGISTRY_USERNAME --password-stdin
      - name: Construir y Subir imagen de docker
        run: |
          BRANCH_NAME=$(basename $GITHUB_REF)
          IMAGE_VERSION=$(date +%s)
          sed -e "s~\${REPO_NAME}~$REPO_NAME~g" \
          -e "s~\${BRANCH_NAME}~${BRANCH_NAME}~g" \
          -e "s~\${REGISTRY_SPACE}~$REGISTRY_SPACE~g" \
          -e "s~\${IMAGE_VERSION}~${IMAGE_VERSION}~g" \
          -e "s~\${REGISTRY_HOST}~$REGISTRY_HOST~g" \
          docker_image_bash.sh > new_docker_image_bash.sh
          bash new_docker_image_bash.sh
          rm -rf new_docker_image_bash.sh
          echo "La imagen $REGISTRY_HOST/$REGISTRY_SPACE/${repo_name}-${BRANCH_NAME}:${IMAGE_VERSION} se construyo y se subió exitosamente"
          echo "La imagen $REGISTRY_HOST/$REGISTRY_SPACE/${repo_name}-${BRANCH_NAME}:latest se construyo y se subió exitosamente"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      REGISTRY_SPACE: ${{ secrets.REGISTRY_SPACE }}
      REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configurar kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.BASE64_KUBECONFIG }}
      - name: desplegar servicio
        run: |
          BRANCH_NAME=$(basename $GITHUB_REF)
          POD_NAMES=$(kubectl get deployment -n ${BRANCH_NAME} --no-headers=true | awk '/micro/{print $1}')
          if [ ! -z "${POD_NAMES}" ]; then
            kubectl rollout restart -n ${BRANCH_NAME} deployment ${POD_NAMES}
          fi
      - name: Eliminar config file y new_deployment
        run: |
          BRANCH_NAME=$(basename $GITHUB_REF)
          echo "Se desplegaron la aplicación y el servicio en la rama ${BRANCH_NAME} de manera exitosa"
          rm -rf $HOME/.kube/config