name: CICD

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Actualizar pip
        run: |
          python -m pip install --upgrade pip
      - name: Verificar archivo requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt no encontrado. No se ejecutará la acción."
            exit 0
          fi
      - name: Instalar dependencias
        run: |
          python -m pip install -r requirements.txt

      - name: Correr tests
        run: |
          pytest
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
      REGISTRY_SPACE: ${{ secrets.REGISTRY_SPACE }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verificar archivo Dockerfile
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile no encontrado. No se ejecutará la acción."
            exit 0
          fi
      - name: Autenticarse en el registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_HOST --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD
      - name: Construir y Subir imagen de docker
        run: |
          BRANCH_NAME=$(basename $GITHUB_REF)
          IMAGE_VERSION=$(date +%s)
          sed -e "s~\${REPO_NAME}~$REPO_NAME~g" \
          -e "s~\${BRANCH_NAME}~${BRANCH_NAME}~g" \
          -e "s~\${REGISTRY_SPACE}~$REGISTRY_SPACE~g" \
          -e "s~\${IMAGE_VERSION}~${IMAGE_VERSION}~g" \
          -e "s~\${REGISTRY_HOST}~$REGISTRY_HOST~g" \
          docker_image_bash.sh > new_docker_image_bash.sh
          bash new_docker_image_bash.sh
          rm -rf new_docker_image_bash.sh
          echo "La imagen $REGISTRY_HOST/$REGISTRY_SPACE/${repo_name}-${BRANCH_NAME}:${IMAGE_VERSION} se construyo y se subió exitosamente"
          echo "La imagen $REGISTRY_HOST/$REGISTRY_SPACE/${repo_name}-${BRANCH_NAME}:latest se construyo y se subió exitosamente"